### ISSUE TITLE
Suggestion: Add dump_for_python.py script

### ISSUE THREAD

**Issue by robnardo** [palto42/ndscheduler#6]
Hi Matthias, 

Thank you for forking, maintaining and adding features to the ndscheduler repo.  I have a suggestion.  While I was trying to migrate the default sqlite database to MySQL I ran into an issue.  The SQL script that the sqlite3 cli .dump script outputs is not compatible with the mysql cli import command.  I did some searching and found something that helped convert the sqlite sql to mysql sql:

https://stackoverflow.com/questions/18671/quick-easy-way-to-migrate-sqlite3-to-mysql

You may find it useful to put this script in a util module and have it triggered from the admin screen.

Cheers,
Rob

**Comment by palto42** [comment]
Hi Rob,
Thanks for your suggestion, but not fully sure if it's worth the effort to integrate it. If I correctly understand it's only required for migration purposes which should happen rarely (once per user per app).
A stand-alone script might be sufficient with some reference/documentation in the README.
Currently I don't have much time for this, but I'm happy to keep this issue open as a todo for later.

Other option would be that you or another user takes it up and submits a PR to this repo.

**Comment by palto42** [comment]
Closing this issue since I don't plant to work on an implementation.
